# ==============================================================================
# ELARA PROXY SERVICE - DEPLOYMENT
# ==============================================================================

apiVersion: apps/v1
kind: Deployment
metadata:
  name: elara-proxy
  namespace: elara-proxy
  labels:
    app: elara-proxy
    component: proxy
    tier: application
spec:
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  selector:
    matchLabels:
      app: elara-proxy
  template:
    metadata:
      labels:
        app: elara-proxy
        component: proxy
        tier: application
    spec:
      serviceAccountName: elara-proxy-sa

      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        fsGroup: 1000
        seccompProfile:
          type: RuntimeDefault

      containers:
      - name: proxy
        image: gcr.io/elara-mvp-13082025-u1/proxy:latest
        imagePullPolicy: Always

        ports:
        - name: http
          containerPort: 8080
          protocol: TCP

        envFrom:
        - configMapRef:
            name: elara-config

        resources:
          requests:
            cpu: 250m
            memory: 512Mi
          limits:
            cpu: 1000m
            memory: 1Gi

        livenessProbe:
          httpGet:
            path: /health
            port: 8080
            scheme: HTTP
          initialDelaySeconds: 20
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3

        readinessProbe:
          httpGet:
            path: /health
            port: 8080
            scheme: HTTP
          initialDelaySeconds: 10
          periodSeconds: 5
          timeoutSeconds: 3
          failureThreshold: 2

        securityContext:
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: false
          capabilities:
            drop: ["ALL"]

        volumeMounts:
        - name: tmp
          mountPath: /tmp
        - name: screenshots
          mountPath: /app/screenshots

      volumes:
      - name: tmp
        emptyDir: {}
      - name: screenshots
        emptyDir:
          sizeLimit: 5Gi
