apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - backend-api/deployment.yaml
  - backend-api/service.yaml
  - worker/deployment.yaml
  - proxy/deployment.yaml
  - frontend-deployment.yaml