/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        // Primary Colors (Sapphire Family)
        primary: {
          50: '#eff6ff',
          100: '#dbeafe',
          200: '#bfdbfe',
          300: '#93c5fd',
          400: '#60a5fa',
          500: '#2563eb',
          600: '#1d4ed8',
          700: '#1e40af',
          800: '#1e3a8a',
          900: '#1e3a70',
          950: '#0f1f47',
        },
        // Accent Colors (Spectral Violet)
        accent: {
          50: '#faf5ff',
          100: '#f3e8ff',
          200: '#e9d5ff',
          300: '#d8b4fe',
          400: '#c084fc',
          500: '#a855f7',
          600: '#9333ea',
          700: '#7e22ce',
          800: '#6b21a8',
          900: '#581c87',
        },
        // Neutral Colors (Blue undertone)
        neutral: {
          0: '#ffffff',
          50: '#f8fafc',
          100: '#f1f5f9',
          200: '#e2e8f0',
          300: '#cbd5e1',
          400: '#94a3b8',
          500: '#64748b',
          600: '#475569',
          700: '#334155',
          800: '#1e293b',
          900: '#0f172a',
          950: '#020617',
        },
        // Severity Scale (Light Mode)
        'severity-light': {
          sev0: {
            bg: '#f0f9ff',
            border: '#bae6fd',
            text: '#0369a1',
            icon: '#0284c7',
          },
          sev1: {
            bg: '#f0fdf4',
            border: '#bbf7d0',
            text: '#15803d',
            icon: '#16a34a',
          },
          sev2: {
            bg: '#fffbeb',
            border: '#fde68a',
            text: '#b45309',
            icon: '#d97706',
          },
          sev3: {
            bg: '#fef3c7',
            border: '#fbbf24',
            text: '#92400e',
            icon: '#f59e0b',
          },
          sev4: {
            bg: '#fef2f2',
            border: '#fecaca',
            text: '#991b1b',
            icon: '#dc2626',
          },
          sev5: {
            bg: '#450a0a',
            border: '#7f1d1d',
            text: '#fecaca',
            icon: '#ef4444',
          },
        },
        // Severity Scale (Dark Mode)
        'severity-dark': {
          sev0: {
            bg: '#0c1e2f',
            border: '#1e3a5f',
            text: '#7dd3fc',
            icon: '#38bdf8',
          },
          sev1: {
            bg: '#0a2e1a',
            border: '#14532d',
            text: '#86efac',
            icon: '#4ade80',
          },
          sev2: {
            bg: '#2e1f0a',
            border: '#78350f',
            text: '#fde047',
            icon: '#facc15',
          },
          sev3: {
            bg: '#3e1f0a',
            border: '#92400e',
            text: '#fbbf24',
            icon: '#f59e0b',
          },
          sev4: {
            bg: '#3e0a0a',
            border: '#7f1d1d',
            text: '#fca5a5',
            icon: '#f87171',
          },
          sev5: {
            bg: '#7f1d1d',
            border: '#dc2626',
            text: '#fef2f2',
            icon: '#ef4444',
          },
        },
        // Functional Colors
        functional: {
          success: {
            bg: '#f0fdf4',
            border: '#86efac',
            text: '#15803d',
            hover: '#dcfce7',
          },
          warning: {
            bg: '#fffbeb',
            border: '#fde68a',
            text: '#b45309',
            hover: '#fef3c7',
          },
          error: {
            bg: '#fef2f2',
            border: '#fecaca',
            text: '#991b1b',
            hover: '#fee2e2',
          },
          info: {
            bg: '#eff6ff',
            border: '#93c5fd',
            text: '#1e40af',
            hover: '#dbeafe',
          },
        },
        // Surface Colors
        surface: {
          base: 'var(--surface-base)',
          elevated: 'var(--surface-elevated)',
          sunken: 'var(--surface-sunken)',
          overlay: 'var(--surface-overlay)',
        },
        // Border Colors
        border: {
          default: 'var(--border-default)',
          strong: 'var(--border-strong)',
          subtle: 'var(--border-subtle)',
          focus: 'var(--border-focus)',
        },
        // Text Colors
        text: {
          primary: 'var(--text-primary)',
          secondary: 'var(--text-secondary)',
          tertiary: 'var(--text-tertiary)',
          disabled: 'var(--text-disabled)',
          inverse: 'var(--text-inverse)',
          link: 'var(--text-link)',
          linkHover: 'var(--text-link-hover)',
        },
      },
      fontFamily: {
        sans: [
          'Inter Variable',
          '-apple-system',
          'BlinkMacSystemFont',
          'Segoe UI',
          'Helvetica',
          'Arial',
          'sans-serif',
        ],
        mono: [
          'JetBrains Mono Variable',
          'Fira Code',
          'Consolas',
          'Courier New',
          'monospace',
        ],
      },
      fontSize: {
        xs: ['0.75rem', { lineHeight: '1rem', letterSpacing: '0.01em' }],
        sm: ['0.875rem', { lineHeight: '1.25rem', letterSpacing: '0.005em' }],
        base: ['1rem', { lineHeight: '1.5rem', letterSpacing: '0' }],
        lg: ['1.125rem', { lineHeight: '1.75rem', letterSpacing: '-0.005em' }],
        xl: ['1.25rem', { lineHeight: '1.875rem', letterSpacing: '-0.01em' }],
        '2xl': ['1.5rem', { lineHeight: '2rem', letterSpacing: '-0.015em' }],
        '3xl': ['1.875rem', { lineHeight: '2.25rem', letterSpacing: '-0.02em' }],
        '4xl': ['2.25rem', { lineHeight: '2.5rem', letterSpacing: '-0.025em' }],
        '5xl': ['3rem', { lineHeight: '1', letterSpacing: '-0.03em' }],
      },
      spacing: {
        0: '0',
        1: '0.25rem',
        2: '0.5rem',
        3: '0.75rem',
        4: '1rem',
        5: '1.25rem',
        6: '1.5rem',
        8: '2rem',
        10: '2.5rem',
        12: '3rem',
        16: '4rem',
        20: '5rem',
        24: '6rem',
      },
      borderRadius: {
        none: '0',
        sm: '0.25rem',
        base: '0.5rem',
        md: '0.75rem',
        lg: '0.875rem',
        xl: '1rem',
        '2xl': '1.5rem',
        full: '9999px',
        notched: '0.75rem',
      },
      boxShadow: {
        xs: '0 1px 2px 0 rgba(15, 23, 42, 0.05)',
        sm: '0 1px 3px 0 rgba(15, 23, 42, 0.1), 0 1px 2px -1px rgba(15, 23, 42, 0.1)',
        base: '0 4px 6px -1px rgba(15, 23, 42, 0.1), 0 2px 4px -2px rgba(15, 23, 42, 0.1)',
        md: '0 10px 15px -3px rgba(15, 23, 42, 0.1), 0 4px 6px -4px rgba(15, 23, 42, 0.1)',
        lg: '0 20px 25px -5px rgba(15, 23, 42, 0.1), 0 8px 10px -6px rgba(15, 23, 42, 0.1)',
        xl: '0 25px 50px -12px rgba(15, 23, 42, 0.25)',
        focus: '0 0 0 3px rgba(37, 99, 235, 0.2)',
      },
      transitionDuration: {
        instant: '50ms',
        fast: '120ms',
        base: '180ms',
        slow: '240ms',
        slower: '360ms',
      },
      transitionTimingFunction: {
        in: 'cubic-bezier(0.4, 0, 1, 1)',
        out: 'cubic-bezier(0, 0, 0.2, 1)',
        inOut: 'cubic-bezier(0.4, 0, 0.2, 1)',
        spring: 'cubic-bezier(0.34, 1.56, 0.64, 1)',
      },
      zIndex: {
        base: '0',
        dropdown: '1000',
        sticky: '1100',
        fixed: '1200',
        overlay: '1300',
        modal: '1400',
        popover: '1500',
        tooltip: '1600',
        toast: '1700',
      },
      keyframes: {
        'spectral-shimmer': {
          '0%': { backgroundPosition: '0% 50%' },
          '50%': { backgroundPosition: '100% 50%' },
          '100%': { backgroundPosition: '0% 50%' },
        },
        'slide-in': {
          '0%': { transform: 'translateY(-8px)', opacity: '0' },
          '100%': { transform: 'translateY(0)', opacity: '1' },
        },
        'slide-out': {
          '0%': { transform: 'translateY(0)', opacity: '1' },
          '100%': { transform: 'translateY(-8px)', opacity: '0' },
        },
        'fade-in': {
          '0%': { opacity: '0' },
          '100%': { opacity: '1' },
        },
        'fade-out': {
          '0%': { opacity: '1' },
          '100%': { opacity: '0' },
        },
        'shimmer': {
          '0%': { transform: 'translateX(-100%)' },
          '100%': { transform: 'translateX(100%)' },
        },
      },
      animation: {
        'spectral-shimmer': 'spectral-shimmer 2s ease infinite',
        'slide-in': 'slide-in 0.18s ease-out',
        'slide-out': 'slide-out 0.18s ease-in',
        'fade-in': 'fade-in 0.18s ease-out',
        'fade-out': 'fade-out 0.18s ease-in',
        shimmer: 'shimmer 1.5s ease-in-out infinite',
      },
    },
  },
  plugins: [],
}
