# PostgreSQL Configuration
# Database: elara_production
# User: elara_app

apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-config
  namespace: elara-database
data:
  POSTGRES_DB: "elara_production"
  POSTGRES_USER: "elara_app"

  # PostgreSQL configuration
  POSTGRES_INITDB_ARGS: "--encoding=UTF8 --locale=en_US.UTF-8"
  PGDATA: "/var/lib/postgresql/data/pgdata"

  # Performance tuning
  shared_buffers: "2GB"
  effective_cache_size: "6GB"
  maintenance_work_mem: "512MB"
  checkpoint_completion_target: "0.9"
  wal_buffers: "16MB"
  default_statistics_target: "100"
  random_page_cost: "1.1"
  effective_io_concurrency: "200"
  work_mem: "10MB"
  min_wal_size: "1GB"
  max_wal_size: "4GB"
  max_worker_processes: "2"
  max_parallel_workers_per_gather: "1"
  max_parallel_workers: "2"
  max_parallel_maintenance_workers: "1"

  # Connection settings
  max_connections: "200"

  # Logging
  log_destination: "stderr"
  logging_collector: "on"
  log_directory: "/var/log/postgresql"
  log_filename: "postgresql-%Y-%m-%d.log"
  log_rotation_age: "1d"
  log_rotation_size: "100MB"
  log_line_prefix: "%t [%p]: [%l-1] user=%u,db=%d,app=%a,client=%h "
  log_timezone: "UTC"

  # Replication
  wal_level: "replica"
  max_wal_senders: "10"
  max_replication_slots: "10"
  hot_standby: "on"
