# PostgreSQL Secrets
# IMPORTANT: Replace placeholder passwords before deploying!
# Use: echo -n 'your-password' | base64

apiVersion: v1
kind: Secret
metadata:
  name: postgres-secrets
  namespace: elara-database
type: Opaque
data:
  # REPLACE THESE WITH ACTUAL BASE64-ENCODED PASSWORDS
  # Example: echo -n 'SuperSecurePassword123!' | base64
  POSTGRES_PASSWORD: UExBQ0VIT0xERVJfUEFTU1dPUkQ=  # PLACEHOLDER_PASSWORD
  POSTGRES_REPLICATION_PASSWORD: UExBQ0VIT0xERVJfUkVQTElDQVRJT05fUEFTU1dPUkQ=  # PLACEHOLDER_REPLICATION_PASSWORD

---
# Application database credentials for backend pods
apiVersion: v1
kind: Secret
metadata:
  name: elara-database-credentials
  namespace: elara-backend-prod
type: Opaque
data:
  # Format: postgresql://elara_app:PASSWORD@postgres-primary.elara-database.svc.cluster.local:5432/elara_production
  DATABASE_URL: UExBQ0VIT0xERVJfREFUQUJBU0VfVVJM  # PLACEHOLDER - Replace after generating passwords
