# PostgreSQL Persistent Storage
# Primary: 200GB SSD
# Cost: $34/month per volume

apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: postgres-ssd
provisioner: kubernetes.io/gce-pd
parameters:
  type: pd-ssd
  replication-type: regional-pd
  fstype: ext4
allowVolumeExpansion: true
volumeBindingMode: WaitForFirstConsumer

---
# Persistent Volume Claim for Primary
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-primary-pvc
  namespace: elara-database
  labels:
    app: postgres
    role: primary
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: postgres-ssd
  resources:
    requests:
      storage: 200Gi

---
# Persistent Volume Claim for Replica
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-replica-pvc
  namespace: elara-database
  labels:
    app: postgres
    role: replica
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: postgres-ssd
  resources:
    requests:
      storage: 200Gi
