# PostgreSQL Monitoring & Alerting
# Prometheus PostgreSQL Exporter

apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-exporter-config
  namespace: elara-database
data:
  queries.yaml: |
    pg_database:
      query: |
        SELECT
          pg_database.datname,
          pg_database_size(pg_database.datname) as size_bytes
        FROM pg_database
      metrics:
        - datname:
            usage: "LABEL"
            description: "Database name"
        - size_bytes:
            usage: "GAUGE"
            description: "Database size in bytes"

    pg_stat_statements:
      query: |
        SELECT
          queryid,
          calls,
          total_exec_time,
          mean_exec_time,
          rows
        FROM pg_stat_statements
        ORDER BY total_exec_time DESC
        LIMIT 10
      metrics:
        - queryid:
            usage: "LABEL"
            description: "Query ID"
        - calls:
            usage: "COUNTER"
            description: "Number of times executed"
        - total_exec_time:
            usage: "COUNTER"
            description: "Total execution time (ms)"
        - mean_exec_time:
            usage: "GAUGE"
            description: "Mean execution time (ms)"
        - rows:
            usage: "COUNTER"
            description: "Total rows retrieved/affected"

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-exporter
  namespace: elara-database
  labels:
    app: postgres-exporter
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres-exporter
  template:
    metadata:
      labels:
        app: postgres-exporter
    spec:
      containers:
      - name: postgres-exporter
        image: prometheuscommunity/postgres-exporter:latest
        ports:
        - name: metrics
          containerPort: 9187
        env:
        - name: DATA_SOURCE_NAME
          value: "postgresql://elara_app:$(POSTGRES_PASSWORD)@postgres-primary.elara-database.svc.cluster.local:5432/elara_production?sslmode=disable"
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: postgres-secrets
              key: POSTGRES_PASSWORD
        - name: PG_EXPORTER_EXTEND_QUERY_PATH
          value: "/config/queries.yaml"
        volumeMounts:
        - name: queries
          mountPath: /config
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "200m"
      volumes:
      - name: queries
        configMap:
          name: postgres-exporter-config

---
apiVersion: v1
kind: Service
metadata:
  name: postgres-exporter
  namespace: elara-database
  labels:
    app: postgres-exporter
spec:
  type: ClusterIP
  ports:
  - name: metrics
    port: 9187
    targetPort: 9187
  selector:
    app: postgres-exporter
