apiVersion: v1
kind: Secret
metadata:
  name: postgres-secrets
  namespace: elara-backend-prod
  labels:
    app: postgresql
    tier: database
type: Opaque
stringData:
  # Main database password
  POSTGRES_PASSWORD: "CHANGEME_DB_PASSWORD"

  # Replication user password
  POSTGRES_REPLICATION_PASSWORD: "CHANGEME_REPLICATION_PASSWORD"

  # Connection string for applications
  DATABASE_URL: "postgresql://elara_app:CHANGEME_DB_PASSWORD@postgres-primary:5432/elara_production?sslmode=require"

  # Read replica connection string
  DATABASE_REPLICA_URL: "postgresql://elara_app:CHANGEME_DB_PASSWORD@postgres-replica:5432/elara_production?sslmode=require"
---
# NOTE: Before deploying, replace CHANGEME_* with actual strong passwords
# Generate strong passwords with:
# openssl rand -base64 32
#
# Then update this file with:
# kubectl create secret generic postgres-secrets \
#   --from-literal=POSTGRES_PASSWORD=$(openssl rand -base64 32) \
#   --from-literal=POSTGRES_REPLICATION_PASSWORD=$(openssl rand -base64 32) \
#   --namespace=elara-backend-prod \
#   --dry-run=client -o yaml | kubectl apply -f -
