# ==============================================================================
# ELARA PLATFORM - PRODUCTION INGRESS
# ==============================================================================

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: elara-ingress
  namespace: elara-backend
  labels:
    app: elara
    environment: production
  annotations:
    # Global HTTPS load balancer
    kubernetes.io/ingress.class: "gce"
    kubernetes.io/ingress.global-static-ip-name: "elara-global-lb-ip"

    # SSL certificates
    networking.gke.io/managed-certificates: "elara-ssl-cert"

    # Cloud Armor security policy
    cloud.google.com/armor-config: '{"elara-security-policy": "elara-security-policy"}'

    # Backend configuration
    cloud.google.com/backend-config: '{"default": "elara-backend-config"}'

    # CDN
    cloud.google.com/cdn-enabled: "true"

    # Session affinity
    cloud.google.com/session-affinity-type: "CLIENT_IP"

    # Connection draining
    cloud.google.com/connection-draining-timeout: "300"

spec:
  rules:
  # API domain
  - host: api.elara.com
    http:
      paths:
      - path: /*
        pathType: ImplementationSpecific
        backend:
          service:
            name: elara-api-service
            port:
              number: 80

  # Main domain (if API is on subdomain)
  - host: elara.com
    http:
      paths:
      - path: /api/*
        pathType: ImplementationSpecific
        backend:
          service:
            name: elara-api-service
            port:
              number: 80

---
# ==============================================================================
# MANAGED SSL CERTIFICATE
# ==============================================================================

apiVersion: networking.gke.io/v1
kind: ManagedCertificate
metadata:
  name: elara-ssl-cert
  namespace: elara-backend
spec:
  domains:
    - elara.com
    - api.elara.com
    - www.elara.com

---
# ==============================================================================
# BACKEND CONFIG (Health check, timeout, session affinity)
# ==============================================================================

apiVersion: cloud.google.com/v1
kind: BackendConfig
metadata:
  name: elara-backend-config
  namespace: elara-backend
spec:
  # Health check configuration
  healthCheck:
    checkIntervalSec: 10
    timeoutSec: 5
    healthyThreshold: 2
    unhealthyThreshold: 3
    type: HTTP
    requestPath: /health
    port: 3001

  # Session affinity
  sessionAffinity:
    affinityType: "CLIENT_IP"
    affinityCookieTtlSec: 10800  # 3 hours

  # Connection draining
  connectionDraining:
    drainingTimeoutSec: 300

  # Timeout
  timeoutSec: 30

  # CDN configuration
  cdn:
    enabled: true
    cachePolicy:
      includeHost: true
      includeProtocol: true
      includeQueryString: false
    negativeCaching: true
    negativeCachingPolicy:
      - code: 404
        ttl: 120
      - code: 410
        ttl: 120

  # IAP (Identity-Aware Proxy) - Optional
  # iap:
  #   enabled: false
  #   oauthclientCredentials:
  #     secretName: oauth-client-secret

  # Security policy reference
  securityPolicy:
    name: "elara-security-policy"
