name: Deploy to Development

on:
  push:
    branches:
      - develop
  workflow_dispatch:

jobs:
  deploy:
    name: Deploy to GKE Development
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Trigger Cloud Build
        run: |
          gcloud builds submit \
            --config=infrastructure/cloudbuild/dev.yaml \
            --substitutions=SHORT_SHA=${{ github.sha }},_ENVIRONMENT=dev \
            --project=${{ secrets.GCP_PROJECT_ID }} \
            .

      - name: Deployment summary
        if: success()
        run: |
          echo "✅ Deployment to Development successful!"
          echo "Backend API: http://35.199.176.26/api"
          echo "Frontend: http://136.117.33.149/"
          echo "Commit: ${{ github.sha }}"

      - name: Deployment failed
        if: failure()
        run: |
          echo "❌ Deployment to Development failed!"
          echo "Check Cloud Build logs at:"
          echo "https://console.cloud.google.com/cloud-build/builds?project=${{ secrets.GCP_PROJECT_ID }}"
